### ISSUE TITLE
Retrieving a content model by `idType: SLUG` returns `null`

### ISSUE THREAD

**Issue by blakewilson** [wpengine/atlas-content-modeler#310] opened 2021-10-06 18:25 UTC
When querying a content model by `id` and `idType` as `SLUG`, the content model returns `null`.

### To reproduce
1. Create a content model
2. Create a few posts in the CPT content model
3. Query for a post by slug:
    ```graphql
    query MyQuery {
      teamMember(id: "42", idType: SLUG) {
        id
        slug
      }
    }
     ```
4. See a `null` response

### Expected behavior
The response should include the post, as it would when using `idType` set to `ID`, `DATABASE_ID`, etc.

### Screenshots
![Screen Shot 2021-10-06 at 1 21 38 PM](https://user-images.githubusercontent.com/5946219/136260967-8f73b3ce-2646-40d7-a12a-74f0d3cbe06c.png)

![Screen Shot 2021-10-06 at 1 21 45 PM](https://user-images.githubusercontent.com/5946219/136261005-94caa525-29df-4abd-b7a3-77b46a33c2b2.png)

### Version information
- Plugin version: 0.7.0
- WordPress version: 5.8.1
- WPGraphQL version: 1.6.5
- Operating system: MacOS
- Browser: Chrome

**Comment by mindctrl** [comment] 2021-10-06 20:07
This appears to be caused by the fact that we don't register post types as `public`. Trying `publicly_queryable` set to true, while `public` still being false, does not fix it. Seems like we might be forced to register with `public => true` for this query type to work.

**Comment by mindctrl** [comment] 2021-10-06 20:15
As a test, commenting out this line in WPGraphQL makes the query work:

https://github.com/wp-graphql/wp-graphql/blob/24d00d1c428b9ef933d167edab61652f6f4a48d6/src/Data/NodeResolver.php#L390

I wonder what the reasoning is for WPGraphQL to check for `public` + `show_in_graphql`. Is the latter not sufficient? If not, is there a chance of changing that to `publicly_queryable` instead? Just looking at all our options here. cc @jasonbahl

**Comment by nickcernis** [comment] 2021-10-07 07:10
> This appears to be caused by the fact that we don't register post types as public.

Related: https://github.com/wpengine/atlas-content-modeler/issues/290.

**Comment by mindctrl** [comment] 2021-12-02 20:07
This was fixed in https://github.com/wp-graphql/wp-graphql/pull/2132

![image](https://user-images.githubusercontent.com/1254870/144494999-e1b348e0-2126-4ad6-aedb-9e331e4e9f79.png)

**Closed by mindctrl** 2021-12-02 20:07 UTC
Labels: bug, wpgraphql
